name: SonarQube Code Quality

on:
  pull_request:
    branches:
      - main
      - develop
      - release/*
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sonar:
    uses: YeisonLondo/Skorify_DevOps_Prueba/.github/workflows/lint-backend.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}